module.exports = {
  restart_syscall: { number: 0,   argc: 0,  func: "sys_restart_syscall" },
  exit:            { number: 1,   argc: 1,  func: "sys_exit"            },
  fork:            { number: 2,   argc: 0,  func: "sys_fork"            },
  read:            { number: 3,   argc: 3,  func: "sys_read"            },
  write:           { number: 4,   argc: 3,  func: "sys_write"           },
  open:            { number: 5,   argc: 3,  func: "sys_open"            },
  close:           { number: 6,   argc: 1,  func: "sys_close"           },
  waitpid:         { number: 7,   argc: 3,  func: "sys_waitpid"         },
  creat:           { number: 8,   argc: 2,  func: "sys_creat"           },
  link:            { number: 9,   argc: 2,  func: "sys_link"            },
  unlink:          { number: 10,  argc: 1,  func: "sys_unlink"          },
  execve:          { number: 11,  argc: 3,  func: "sys_execve"          },
  chdir:           { number: 12,  argc: 1,  func: "sys_chdir"           },
  time:            { number: 13,  argc: 1,  func: "sys_time32"          },
  mknod:           { number: 14,  argc: 3,  func: "sys_mknod"           },
  chmod:           { number: 15,  argc: 2,  func: "sys_chmod"           },
  //lchown16: { number: 16,  argc: 3 },
  lseek:           { number: 19,  argc: 3,  func: "sys_lseek"           },
  getpid:          { number: 20,  argc: 0,  func: "sys_getpid"          },
  mount:           { number: 21,  argc: 5,  func: "sys_mount"           },

  brk:             { number: 45,  argc: 1,  func: "sys_brk"             },
  ioctl:           { number: 54,  argc: 3,  func: "sys_ioctl"           },
  dup2:            { number: 63,  argc: 2,  func: "sys_dup2"            },
  gettimeofday:    { number: 78,  argc: 2,  func: "sys_gettimeofday"    },
  _llseek:         { number: 140, argc: 5,  func: "sys_llseek"          },
  readv:           { number: 145, argc: 3,  func: "sys_readv"           },
  writev:          { number: 146, argc: 3,  func: "sys_writev"          },
  rt_sigaction:    { number: 174, argc: 4,  func: "sys_rt_sigaction"    },
  rt_sigprocmask:  { number: 175, argc: 4,  func: "sys_rt_sigprocmask"  },
  getcwd:          { number: 183, argc: 2,  func: "sys_getcwd"          },

  getuid32:        { number: 199, argc: 0,  func: "sys_getuid"          },
  getgid32:        { number: 200, argc: 0,  func: "sys_getgid"          },
  geteuid32:       { number: 201, argc: 0,  func: "sys_geteuid"         },
  getegid32:       { number: 202, argc: 0,  func: "sys_getegid"         },

  gettid:          { number: 224, argc: 0,  func: "sys_gettid"          },
  futex:           { number: 240, argc: 6,  func: "sys_futex_time32"    },			
}
