/*
 *
 *  Copyright (C) 2025  Yurii Yakubin (yurii.yakubin@gmail.com)
 *
 */

#ifndef _GNU_VERSIONS_H
#define _GNU_VERSIONS_H

#cmakedefine _GNU_OBSTACK_INTERFACE_VERSION @CONFIG_OBSTACK_INTERFACE_VERSION@
#cmakedefine _GNU_REGEX_INTERFACE_VERSION   @CONFIG_REGEX_INTERFACE_VERSION@
#cmakedefine _GNU_GLOB_INTERFACE_VERSION    @CONFIG_GLOB_INTERFACE_VERSION@
#cmakedefine _GNU_GETOPT_INTERFACE_VERSION  @CONFIG_GETOPT_INTERFACE_VERSION@

#endif /* _GNU_VERSIONS_H */
