
/*
 *
 *  Copyright (C) 2024-2026  Yurii Yakubin (yurii.yakubin@gmail.com)
 *
 */

#include <wasmux-config.h>
#include <wasmux/section.h>

WA_CUSTOM_SECTION_STR(WASMUX_VERSION_SECTION, WASMUX_VERSION);
WA_CUSTOM_SECTION_STR(WASMUX_DESCRIPTION_SECTION, WASMUX_DESCRIPTION);
WA_CUSTOM_SECTION_STR(WASMUX_URL_SECTION, WASMUX_URL);
