set(_WX_VARIABLE_LIST "")

macro (WX_VARIABLE _name _desc _value _type)
  if (${_type} STREQUAL BOOLEAN)
    option(${_name} "${_desc}" ${_value})
  elseif (${_type} STREQUAL NUMBER)
    set(${_name} ${_value} CACHE STRING "${_desc}")
  elseif (${_type} STREQUAL STRING)
    set(${_name} "${_value}" CACHE STRING "${_desc}")
  elseif (${_type} STREQUAL ENUM)
    set(${_name} "${_value}" CACHE STRING "${_desc}")
    set_property(CACHE ${_name} PROPERTY STRINGS ${ARGN})
  else ()
    message(FATAL_ERROR "Unknown '${_type}' type used for '${_name}' option")
  endif ()

  set(_WX_VARIABLE_${_name}_DESC  "${_desc}")
  set(_WX_VARIABLE_${_name}_VALUE "${_value}")
  set(_WX_VARIABLE_${_name}_TYPE  "${_type}")

  list(APPEND _WX_VARIABLE_LIST ${_name})
endmacro ()

function (WX_VARIABLE_PRINT)
  set(_max_length 0)
  foreach (_name ${_WX_VARIABLE_LIST})
    string(LENGTH "${_name}" _length)
    if (${_length} GREATER ${_max_length})
      set(_max_length ${_length})
    endif ()
  endforeach ()
  math(EXPR _max_space_length "(${_max_length} + 4) / 2")
  string(REPEAT " ." ${_max_space_length} _max_space)

  foreach (_name ${_WX_VARIABLE_LIST})
    string(LENGTH "${_name}" _length)
    string(SUBSTRING "${_max_space}" ${_length} -1 _space)
    message(STATUS "${_name}:${_space} ${_WX_VARIABLE_${_name}_VALUE}")
  endforeach ()
endfunction ()

function (WX_VARIABLE_SAVE _filename)
  set(_content "")

  list(APPEND _content "/*")
  list(APPEND _content " * Automatically generated file (DO NOT EDIT)")
  list(APPEND _content " * WASMUX Configuration")
  list(APPEND _content " */")
  list(APPEND _content "")

  foreach (_name ${_WX_VARIABLE_LIST})
    list(APPEND _content "/* ${_WX_VARIABLE_${_name}_DESC} */")
    set(_type ${_WX_VARIABLE_${_name}_TYPE})
    if (${_type} STREQUAL BOOLEAN)
      if (_WX_VARIABLE_${_name}_VALUE)
        list(APPEND _content "#define ${_name} 1")
      else ()
        list(APPEND _content "#define ${_name} 0")
      endif ()
    elseif (${_type} STREQUAL NUMBER)
      list(APPEND _content "#define ${_name} ${_WX_VARIABLE_${_name}_VALUE}")
    else (${_type} STREQUAL STRING)
      list(APPEND _content "#define ${_name} \"${_WX_VARIABLE_${_name}_VALUE}\"")
    endif ()
    list(APPEND _content "")
  endforeach ()

  string(REPLACE ";" "\n" _content "${_content}")

  get_filename_component(_dir "${_filename}" DIRECTORY)
  make_directory("${_dir}")

  file(WRITE "${_filename}.save" "${_content}")

  execute_process(COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${_filename}.save" "${_filename}")
endfunction ()

WX_VARIABLE(WASMUX_VERSION     "WASMUX Version"      "${PROJECT_VERSION}"       STRING)
WX_VARIABLE(WASMUX_DESCRIPTION "WASMUX Description"  "${PROJECT_DESCRIPTION}"   STRING)
WX_VARIABLE(WASMUX_URL         "WASMUX URL"          "${PROJECT_HOMEPAGE_URL}"  STRING)

WX_VARIABLE(CONFIG_ENABLE_INSTALL_HEADERS  "Enable install headers"                 ON  BOOLEAN)
WX_VARIABLE(CONFIG_ENABLE_TLS              "Enable thread-local storage"            ON  BOOLEAN)
WX_VARIABLE(CONFIG_ENABLE_KERNEL           "Enable kernel installation"             OFF BOOLEAN)
WX_VARIABLE(CONFIG_ENABLE_LIBGCC           "Enable libgcc library"                  ON  BOOLEAN)
WX_VARIABLE(CONFIG_ENABLE_LIBC             "Enable libc library"                    ON  BOOLEAN)
WX_VARIABLE(CONFIG_ENABLE_CRT              "Enable C Run-Time"                      ON  BOOLEAN)
WX_VARIABLE(CONFIG_ENABLE_LIBM             "Enable Math library"                    ON  BOOLEAN)
WX_VARIABLE(CONFIG_ENABLE_DL               "Enable Dynamic library"                 ON  BOOLEAN)
WX_VARIABLE(CONFIG_ENABLE_LIBCXX           "Enable libc++ library"                  ON  BOOLEAN)
WX_VARIABLE(CONFIG_ENABLE_PTHREAD          "Enable pthread library"                 ON  BOOLEAN)
WX_VARIABLE(CONFIG_ENABLE_MAIN_ENV_ARG     "Enable env argument for main function"  OFF BOOLEAN)
WX_VARIABLE(CONFIG_ENABLE_WAEDITOR         "Enable waeditor tool"                   OFF BOOLEAN)

WX_VARIABLE(CONFIG_CORE_INIT_PAGES         "Initial size of core pages"             16  NUMBER)
WX_VARIABLE(CONFIG_CORE_MAX_PAGES          "Maximum size of core pages"             124 NUMBER)

WX_VARIABLE(CONFIG_TARGET_SYSTEM "Target system"                "wasm32" ENUM "wasm32" "wasm64" "wasm32-wasi" "wasm64-wasi")
WX_VARIABLE(CONFIG_LIBC_FEATURES "Choosing features for libc"   "glibc"  ENUM "none" "glibc" "uclibc")

if (CONFIG_ENABLE_LIBC)
  WX_VARIABLE(CONFIG_MALLOC_PATH     "Path to malloc standalone"     "${WASMUX_ROOT_DIR}/uapi/malloc"     STRING)
  WX_VARIABLE(CONFIG_STRING_PATH     "Path to string standalone"     "${WASMUX_ROOT_DIR}/uapi/string"     STRING)
  WX_VARIABLE(CONFIG_CTYPE_PATH      "Path to ctype standalone"      "${WASMUX_ROOT_DIR}/uapi/ctype"      STRING)
  WX_VARIABLE(CONFIG_STDLIB_PATH     "Path to stdlib standalone"     "${WASMUX_ROOT_DIR}/uapi/stdlib"     STRING)
  WX_VARIABLE(CONFIG_SIGNAL_PATH     "Path to signal standalone"     "${WASMUX_ROOT_DIR}/uapi/signal"     STRING)
  WX_VARIABLE(CONFIG_SEMAPHORE_PATH  "Path to semaphore standalone"  "${WASMUX_ROOT_DIR}/uapi/semaphore"  STRING)
  WX_VARIABLE(CONFIG_WCSMBS_PATH     "Path to wcsmbs standalone"     "${WASMUX_ROOT_DIR}/uapi/wcsmbs"     STRING)
  WX_VARIABLE(CONFIG_LIBIO_PATH      "Path to libio standalone"      "${WASMUX_ROOT_DIR}/uapi/libio"      STRING)
  WX_VARIABLE(CONFIG_DIRENT_PATH     "Path to dirent standalone"     "${WASMUX_ROOT_DIR}/uapi/dirent"     STRING)
  WX_VARIABLE(CONFIG_GRP_PATH        "Path to grp standalone"        "${WASMUX_ROOT_DIR}/uapi/grp"        STRING)
  WX_VARIABLE(CONFIG_PWD_PATH        "Path to pwd standalone"        "${WASMUX_ROOT_DIR}/uapi/pwd"        STRING)
  WX_VARIABLE(CONFIG_FTW_PATH        "Path to ftw standalone"        "${WASMUX_ROOT_DIR}/uapi/ftw"        STRING)
  WX_VARIABLE(CONFIG_WORDEXP_PATH    "Path to wordexp standalone"    "${WASMUX_ROOT_DIR}/uapi/wordexp"    STRING)
  WX_VARIABLE(CONFIG_LOGIN_PATH      "Path to login standalone"      "${WASMUX_ROOT_DIR}/uapi/login"      STRING)
  WX_VARIABLE(CONFIG_MNTENT_PATH     "Path to mntent standalone"     "${WASMUX_ROOT_DIR}/uapi/mntent"     STRING)
  WX_VARIABLE(CONFIG_SHADOW_PATH     "Path to shadow standalone"     "${WASMUX_ROOT_DIR}/uapi/shadow"     STRING)
  WX_VARIABLE(CONFIG_TERMIOS_PATH    "Path to termios standalone"    "${WASMUX_ROOT_DIR}/uapi/termios"    STRING)
  WX_VARIABLE(CONFIG_ARGP_PATH       "Path to argp standalone"       "${WASMUX_ROOT_DIR}/uapi/argp"       STRING)
  WX_VARIABLE(CONFIG_FTS_PATH        "Path to fts standalone"        "${WASMUX_ROOT_DIR}/uapi/fts"        STRING)
  WX_VARIABLE(CONFIG_NETDB_PATH      "Path to netdb standalone"      "${WASMUX_ROOT_DIR}/uapi/netdb"      STRING)
  WX_VARIABLE(CONFIG_OBSTACK_PATH    "Path to obstack standalone"    "${WASMUX_ROOT_DIR}/uapi/obstack"    STRING)
  WX_VARIABLE(CONFIG_LIBINTL_PATH    "Path to libintl standalone"    "${WASMUX_ROOT_DIR}/uapi/libintl"    STRING)
  WX_VARIABLE(CONFIG_LOCALE_PATH     "Path to locale standalone"     "${WASMUX_ROOT_DIR}/uapi/locale"     STRING)
  WX_VARIABLE(CONFIG_GETOPT_PATH     "Path to getopt standalone"     "${WASMUX_ROOT_DIR}/uapi/getopt"     STRING)
  WX_VARIABLE(CONFIG_REGEX_PATH      "Path to regex standalone"      "${WASMUX_ROOT_DIR}/uapi/regex"      STRING)
  WX_VARIABLE(CONFIG_GLOB_PATH       "Path to glob standalone"       "${WASMUX_ROOT_DIR}/uapi/glob"       STRING)
  WX_VARIABLE(CONFIG_FNMATCH_PATH    "Path to fnmatch standalone"    "${WASMUX_ROOT_DIR}/uapi/fnmatch"    STRING)
  WX_VARIABLE(CONFIG_ULINUX_PATH     "Path to ulinux standalone"     "${WASMUX_ROOT_DIR}/uapi/ulinux"     STRING)
endif ()

if (CONFIG_ENABLE_KERNEL)
  WX_VARIABLE(CONFIG_JSDATA_PATH     "Path to jsdata standalone"     "${WASMUX_ROOT_DIR}/kernel/jsdata"   STRING)
endif ()
